# Configureation file
rest-server:
  version: v2
  configWatcher: true
  statisticTimer: true
server:
  location:
    tracelocation: ${CURDIR}/logs/trace.log
    serverlocation: ${CURDIR}/logs/server.log
    loglevel: info
    maxsize: 0
    maxbackups: 0
    maxage: 0
    compress: true
  service:
    - port: 8030
      type: http
    - port: 8033
      type: https
      certificate: ${CURDIR}/keys/certificate.pem
      key: ${CURDIR}/keys/key.pem
  JWT:
    issuer: clutron.de
    expire: 14400
    encrypt: true
    publicKey: ${CURDIR}/keys/apiKey.pem
    privateKey: ${CURDIR}/keys/apiKey.prv
  login:
    authenticationServer:
      - type: file
        passwordFile: configuration/realm.properties
      - type: system
  content: ${CURDIR}/static
  plugins: ${CURDIR}/plugins
  shutdown:
    passcode: {}
    # Password to shutdown, will be send encrypted
database:
  modelling:
    Modeling:
      - Database: DBname
        SourceTable: xxx
        SourceField: ""
        DestinationTable: ""
        DestinationField: ""
  access:
    databases:
      - driver: postgres
        target: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/Bitgarten
        table: xxx
#     - driver: mysql
#       url: admin:Testtkn1+@tcp(lion.fritz.box:3306)/Bitgarten
#       table: xxx
tasks:
  use_role: true
  directory: ${CURDIR}/log
  database:
    table: Jobs
fileTransfer:
  Admin:
    role: xxx
  directories:
    directory:
      - name: abc
        location: ${CURDIR}
