# Configureation file
rest-server:
  version: v2
  configWatcher: true
  statisticTimer: true
server:
  location:
    tracelocation: ${DATADIR}/logs/trace.log
    serverlocation: ${DATADIR}/logs/server.log
    loglevel: info
    maxsize: 0
    maxbackups: 0
    maxage: 0
    compress: true
  service:
    - port: 8030
      type: http
    - port: 8033
      type: https
      certificate: ${DATADIR}/keys/certificate.pem
      key: ${DATADIR}/keys/key.pem
  JWT:
    issuer: clutron.de
    expire: 14400
    encrypt: true
    publicKey: ${DATADIR}/keys/certificate.pem
    privateKey: ${DATADIR}/keys/key.pem
  login:
    administrators: ${CURDIR}/configuration/administrator.yaml
    users: ${CURDIR}/configuration/users.yaml
    authenticationServer:
      - type: file
        passwordFile: ${DATADIR}/configuration/realm.properties
      - module: SELECT 1
        type: SQL
        driver: pgx
        target: postgres://<user>:<password>@${POSTGRES_HOST}:${POSTGRES_PORT}/bitgarten
  content: ${HOME}/static
  plugins: ${HOME}/plugins
  shutdown:
    passcode: {}
    # Password to shutdown, will be send encrypted
database:
  modelling:
    Modeling:
      - Database: DBname
        SourceTable: xxx
        SourceField: ""
        DestinationTable: ""
        DestinationField: ""
  access:
    databases:
      - driver: postgres
        target: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASS}
      - driver: mysql
        target: ${MYSQL_USER}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}
        user: ${MYSQL_PORT}
        password: ${MYSQL_PASS}
  sessionInfo:
    deleteUUID: false
    database:
        driver: postgres
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASS}
        target: ${POSTGRES_URL}
        table: "session_info"
  userInfo:
        driver: postgres
        target: ${POSTGRES_URL}
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASS}
        table: "user_info"
  batchRepository:
        driver: postgres
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASS}
        target: ${POSTGRES_URL}
        table: "batch_repo"
tasks:
  use_role: true
  directory: ${DATADIR}/log
  database:
    table: Jobs
fileTransfer:
  Admin:
    role: xxx
  directories:
    directory:
      - name: abc
        location: ${DATADIR}
