#!/bin/bash
#=============================================================================
# Copyright 2022-2023 Thorsten A. Knieling
#
# SPDX-License-Identifier: Apache-2.0
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#=============================================================================
#set -xv

# Environment setup
INSTALL_DIR=/opt/cluapi
REST_SERVER=${INSTALL_DIR}/

exit 0
