// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBasicAuth handles BasicAuth security.
	// HTTP Basic Authentication. Works over `HTTP` and `HTTPS`.
	HandleBasicAuth(ctx context.Context, operationName OperationName, t BasicAuth) (context.Context, error)
	// HandleBearerAuth handles BearerAuth security.
	// HTTP Bearer Authentication. Works over `HTTP` and `HTTPS`.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleTokenCheck handles tokenCheck security.
	// HTTP Basic Authentication. Works over `HTTP` and `HTTPS`.
	HandleTokenCheck(ctx context.Context, operationName string, t TokenCheck) (context.Context, error)
	// Request call after receiving
	Request(ctx context.Context, req *http.Request)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBasicAuth = map[string][]string{
	AddViewOperation:               []string{},
	BatchParameterQueryOperation:   []string{},
	BatchQueryOperation:            []string{},
	BatchSelectOperation:           []string{},
	BrowseListOperation:            []string{},
	BrowseLocationOperation:        []string{},
	CallExtendOperation:            []string{},
	CallPostExtendOperation:        []string{},
	CreateDirectoryOperation:       []string{},
	DeleteExtendOperation:          []string{},
	DeleteFileLocationOperation:    []string{},
	DeleteJobResultOperation:       []string{},
	DeleteRecordsSearchedOperation: []string{},
	DeleteViewOperation:            []string{},
	DownloadFileOperation:          []string{},
	GetConfigOperation:             []string{},
	GetDatabasesOperation:          []string{},
	GetFieldsOperation:             []string{},
	GetImageOperation:              []string{},
	GetJobExecutionResultOperation: []string{},
	GetJobFullInfoOperation:        []string{},
	GetJobResultOperation:          []string{},
	GetJobsOperation:               []string{},
	GetJobsConfigOperation:         []string{},
	GetLobByMapOperation:           []string{},
	GetLoginSessionOperation:       []string{},
	GetMapMetadataOperation:        []string{},
	GetMapRecordsFieldsOperation:   []string{},
	GetMapsOperation:               []string{},
	GetVideoOperation:              []string{},
	GetViewsOperation:              []string{},
	InsertMapFileRecordsOperation:  []string{},
	InsertRecordOperation:          []string{},
	ListModellingOperation:         []string{},
	ListTablesOperation:            []string{},
	LoginSessionOperation:          []string{},
	LogoutSessionCompatOperation:   []string{},
	PostDatabaseOperation:          []string{},
	PostJobOperation:               []string{},
	PushLoginSessionOperation:      []string{},
	RemoveSessionCompatOperation:   []string{},
	SearchModellingOperation:       []string{},
	SearchRecordsFieldsOperation:   []string{},
	SearchTableOperation:           []string{},
	SetConfigOperation:             []string{},
	SetJobsConfigOperation:         []string{},
	ShutdownServerOperation:        []string{},
	StoreConfigOperation:           []string{},
	TriggerExtendOperation:         []string{},
	TriggerJobOperation:            []string{},
	UpdateLobByMapOperation:        []string{},
	UpdateRecordsByFieldsOperation: []string{},
	UploadFileOperation:            []string{},
}

func (s *Server) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BasicAuth
	if _, ok := findAuthorization(req.Header, "Basic"); !ok {
		return ctx, false, nil
	}
	username, password, ok := req.BasicAuth()
	if !ok {
		return nil, false, errors.New("invalid basic auth")
	}
	t.Username = username
	t.Password = password
	t.Roles = operationRolesBasicAuth[operationName]
	rctx, err := s.sec.HandleBasicAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	// CLU TKN addition
	s.sec.Request(rctx, req)

	return rctx, true, err
}

var operationRolesBearerAuth = map[string][]string{
	AddViewOperation: []string{
		"admin",
	},
	BatchParameterQueryOperation: []string{
		"admin",
	},
	BatchQueryOperation: []string{
		"admin",
	},
	BatchSelectOperation: []string{
		"admin",
	},
	BrowseListOperation: []string{
		"admin",
	},
	BrowseLocationOperation: []string{
		"admin",
	},
	CallExtendOperation: []string{
		"admin",
	},
	CallPostExtendOperation: []string{
		"admin",
	},
	CreateDirectoryOperation: []string{
		"admin",
	},
	DeleteExtendOperation: []string{
		"admin",
	},
	DeleteFileLocationOperation: []string{
		"admin",
	},
	DeleteJobResultOperation: []string{
		"admin",
	},
	DeleteRecordsSearchedOperation: []string{
		"user",
	},
	DeleteViewOperation: []string{
		"admin",
	},
	DownloadFileOperation: []string{
		"admin",
	},
	GetConfigOperation: []string{
		"admin",
	},
	GetDatabasesOperation: []string{
		"admin",
	},
	GetFieldsOperation: []string{
		"user",
	},
	GetImageOperation: []string{
		"user",
	},
	GetJobExecutionResultOperation: []string{
		"admin",
	},
	GetJobFullInfoOperation: []string{
		"admin",
	},
	GetJobResultOperation: []string{
		"admin",
	},
	GetJobsOperation: []string{
		"admin",
	},
	GetJobsConfigOperation: []string{
		"admin",
	},
	GetLobByMapOperation: []string{
		"user",
	},
	GetMapMetadataOperation: []string{
		"user",
	},
	GetMapRecordsFieldsOperation: []string{
		"user",
	},
	GetMapsOperation: []string{
		"user",
	},
	GetVideoOperation: []string{
		"user",
	},
	GetViewsOperation: []string{
		"admin",
	},
	InsertMapFileRecordsOperation: []string{
		"user",
	},
	InsertRecordOperation: []string{
		"user",
	},
	ListModellingOperation: []string{
		"user",
	},
	ListTablesOperation: []string{
		"user",
	},
	LogoutSessionCompatOperation: []string{
		"user",
	},
	PostDatabaseOperation: []string{
		"admin",
	},
	PostJobOperation: []string{
		"admin",
	},
	RemoveSessionCompatOperation: []string{
		"user",
	},
	SearchModellingOperation: []string{
		"user",
	},
	SearchRecordsFieldsOperation: []string{
		"user",
	},
	SearchTableOperation: []string{
		"user",
	},
	SetConfigOperation: []string{
		"admin",
	},
	SetJobsConfigOperation: []string{
		"admin",
	},
	ShutdownServerOperation: []string{
		"admin",
	},
	StoreConfigOperation: []string{
		"admin",
	},
	TriggerExtendOperation: []string{
		"admin",
	},
	TriggerJobOperation: []string{
		"admin",
	},
	UpdateLobByMapOperation: []string{
		"user",
	},
	UpdateRecordsByFieldsOperation: []string{
		"user",
	},
	UploadFileOperation: []string{
		"admin",
	},
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	// CLU TKN addition
	s.sec.Request(rctx, req)

	return rctx, true, err
}

var operationRolesTokenCheck = map[string][]string{
	AddViewOperation:               []string{},
	BatchParameterQueryOperation:   []string{},
	BatchQueryOperation:            []string{},
	BatchSelectOperation:           []string{},
	BrowseListOperation:            []string{},
	BrowseLocationOperation:        []string{},
	CallExtendOperation:            []string{},
	CallPostExtendOperation:        []string{},
	CreateDirectoryOperation:       []string{},
	DeleteExtendOperation:          []string{},
	DeleteFileLocationOperation:    []string{},
	DeleteJobResultOperation:       []string{},
	DeleteRecordsSearchedOperation: []string{},
	DeleteViewOperation:            []string{},
	DownloadFileOperation:          []string{},
	GetConfigOperation:             []string{},
	GetDatabasesOperation:          []string{},
	GetFieldsOperation:             []string{},
	GetImageOperation:              []string{},
	GetJobExecutionResultOperation: []string{},
	GetJobFullInfoOperation:        []string{},
	GetJobResultOperation:          []string{},
	GetJobsOperation:               []string{},
	GetJobsConfigOperation:         []string{},
	GetLobByMapOperation:           []string{},
	GetLoginSessionOperation:       []string{},
	GetMapMetadataOperation:        []string{},
	GetMapRecordsFieldsOperation:   []string{},
	GetMapsOperation:               []string{},
	GetVideoOperation:              []string{},
	GetViewsOperation:              []string{},
	InsertMapFileRecordsOperation:  []string{},
	InsertRecordOperation:          []string{},
	ListModellingOperation:         []string{},
	ListTablesOperation:            []string{},
	LoginSessionOperation:          []string{},
	LogoutSessionCompatOperation:   []string{},
	PostDatabaseOperation:          []string{},
	PostJobOperation:               []string{},
	PushLoginSessionOperation:      []string{},
	RemoveSessionCompatOperation:   []string{},
	SearchModellingOperation:       []string{},
	SearchRecordsFieldsOperation:   []string{},
	SearchTableOperation:           []string{},
	SetConfigOperation:             []string{},
	SetJobsConfigOperation:         []string{},
	ShutdownServerOperation:        []string{},
	StoreConfigOperation:           []string{},
	TriggerExtendOperation:         []string{},
	TriggerJobOperation:            []string{},
	UpdateLobByMapOperation:        []string{},
	UpdateRecordsByFieldsOperation: []string{},
	UploadFileOperation:            []string{},
}

func (s *Server) securityTokenCheck(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TokenCheck
	const parameterName = "X-Tokencheck"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTokenCheck[operationName]
	rctx, err := s.sec.HandleTokenCheck(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	// CLU TKN addition
	s.sec.Request(rctx, req)

	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BasicAuth provides BasicAuth security value.
	// HTTP Basic Authentication. Works over `HTTP` and `HTTPS`.
	BasicAuth(ctx context.Context, operationName OperationName) (BasicAuth, error)
	// BearerAuth provides BearerAuth security value.
	// HTTP Bearer Authentication. Works over `HTTP` and `HTTPS`.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
	// TokenCheck provides tokenCheck security value.
	// HTTP Basic Authentication. Works over `HTTP` and `HTTPS`.
	TokenCheck(ctx context.Context, operationName OperationName) (TokenCheck, error)
}

func (s *Client) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BasicAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BasicAuth\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityTokenCheck(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TokenCheck(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TokenCheck\"")
	}
	req.Header.Set("X-Tokencheck", t.APIKey)
	return nil
}
