// Code generated by ogen, DO NOT EDIT.
package api

type AddViewRes interface {
	addViewRes()
}

type BatchParameterQueryRes interface {
	batchParameterQueryRes()
}

type BatchQueryReq interface {
	batchQueryReq()
}

type BatchQueryRes interface {
	batchQueryRes()
}

type BatchSelectRes interface {
	batchSelectRes()
}

type BrowseListRes interface {
	browseListRes()
}

type BrowseLocationRes interface {
	browseLocationRes()
}

type CallExtendRes interface {
	callExtendRes()
}

type CallPostExtendRes interface {
	callPostExtendRes()
}

type CreateDirectoryRes interface {
	createDirectoryRes()
}

type DeleteExtendRes interface {
	deleteExtendRes()
}

type DeleteFileLocationRes interface {
	deleteFileLocationRes()
}

type DeleteJobResultRes interface {
	deleteJobResultRes()
}

type DeleteRecordsSearchedRes interface {
	deleteRecordsSearchedRes()
}

type DeleteViewRes interface {
	deleteViewRes()
}

type DownloadFileRes interface {
	downloadFileRes()
}

type GetConfigRes interface {
	getConfigRes()
}

type GetDatabasesRes interface {
	getDatabasesRes()
}

type GetFieldsRes interface {
	getFieldsRes()
}

type GetImageRes interface {
	getImageRes()
}

type GetJobExecutionResultRes interface {
	getJobExecutionResultRes()
}

type GetJobFullInfoRes interface {
	getJobFullInfoRes()
}

type GetJobResultRes interface {
	getJobResultRes()
}

type GetJobsConfigRes interface {
	getJobsConfigRes()
}

type GetJobsRes interface {
	getJobsRes()
}

type GetLobByMapRes interface {
	getLobByMapRes()
}

type GetLoginSessionRes interface {
	getLoginSessionRes()
}

type GetMapMetadataRes interface {
	getMapMetadataRes()
}

type GetMapRecordsFieldsRes interface {
	getMapRecordsFieldsRes()
}

type GetMapsRes interface {
	getMapsRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type GetVersionRes interface {
	getVersionRes()
}

type GetVideoRes interface {
	getVideoRes()
}

type GetViewsRes interface {
	getViewsRes()
}

type InsertMapFileRecordsRes interface {
	insertMapFileRecordsRes()
}

type InsertRecordRes interface {
	insertRecordRes()
}

type ListModellingRes interface {
	listModellingRes()
}

type ListTablesRes interface {
	listTablesRes()
}

type LoginSessionRes interface {
	loginSessionRes()
}

type LogoutSessionCompatRes interface {
	logoutSessionCompatRes()
}

type PostDatabaseRes interface {
	postDatabaseRes()
}

type PostJobReq interface {
	postJobReq()
}

type PostJobRes interface {
	postJobRes()
}

type PushLoginSessionRes interface {
	pushLoginSessionRes()
}

type RemoveSessionCompatRes interface {
	removeSessionCompatRes()
}

type SearchModellingRes interface {
	searchModellingRes()
}

type SearchRecordsFieldsRes interface {
	searchRecordsFieldsRes()
}

type SearchTableRes interface {
	searchTableRes()
}

type SetConfigReq interface {
	setConfigReq()
}

type SetConfigRes interface {
	setConfigRes()
}

type SetJobsConfigRes interface {
	setJobsConfigRes()
}

type ShutdownServerRes interface {
	shutdownServerRes()
}

type StoreConfigRes interface {
	storeConfigRes()
}

type TriggerExtendRes interface {
	triggerExtendRes()
}

type TriggerJobRes interface {
	triggerJobRes()
}

type UpdateLobByMapReq interface {
	updateLobByMapReq()
}

type UpdateLobByMapRes interface {
	updateLobByMapRes()
}

type UpdateRecordsByFieldsRes interface {
	updateRecordsByFieldsRes()
}

type UploadFileRes interface {
	uploadFileRes()
}
