// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *DatabaseConfig) setDefaults() {
	{
		val := bool(false)
		s.Changed.SetTo(val)
	}
	{
		val := bool(false)
		s.Deleted.SetTo(val)
	}
}
