// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/uri"
)

// EncodeURI encodes CallExtendParams as URI form.
func (s *CallExtendParams) EncodeURI(e uri.Encoder) error {
	return nil
}

var uriFieldsNameOfCallExtendParams = [0]string{}

// DecodeURI decodes CallExtendParams from URI form.
func (s *CallExtendParams) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CallExtendParams to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		default:
			return nil
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode CallExtendParams")
	}

	return nil
}
