// Code generated by ogen, DO NOT EDIT.
package api

type AccessRes interface {
	accessRes()
}

type AdaptPermissionRes interface {
	adaptPermissionRes()
}

type AddAccessRes interface {
	addAccessRes()
}

type AddRBACResourceRes interface {
	addRBACResourceRes()
}

type AddViewRes interface {
	addViewRes()
}

type BatchQueryRes interface {
	batchQueryRes()
}

type BrowseListRes interface {
	browseListRes()
}

type BrowseLocationRes interface {
	browseLocationRes()
}

type CreateDirectoryRes interface {
	createDirectoryRes()
}

type DatabaseOperationRes interface {
	databaseOperationRes()
}

type DatabasePostOperationsRes interface {
	databasePostOperationsRes()
}

type DelAccessRes interface {
	delAccessRes()
}

type DeleteDatabaseRes interface {
	deleteDatabaseRes()
}

type DeleteFileLocationRes interface {
	deleteFileLocationRes()
}

type DeleteJobResultRes interface {
	deleteJobResultRes()
}

type DeleteRBACResourceRes interface {
	deleteRBACResourceRes()
}

type DeleteRecordsSearchedRes interface {
	deleteRecordsSearchedRes()
}

type DeleteViewRes interface {
	deleteViewRes()
}

type DisconnectTCPRes interface {
	disconnectTCPRes()
}

type DownloadFileRes interface {
	downloadFileRes()
}

type GetConfigRes interface {
	getConfigRes()
}

type GetConnectionsRes interface {
	getConnectionsRes()
}

type GetDatabaseSessionsRes interface {
	getDatabaseSessionsRes()
}

type GetDatabaseStatsRes interface {
	getDatabaseStatsRes()
}

type GetDatabasesRes interface {
	getDatabasesRes()
}

type GetEnvironmentsRes interface {
	getEnvironmentsRes()
}

type GetFieldsRes interface {
	getFieldsRes()
}

type GetImageRes interface {
	getImageRes()
}

type GetJobExecutionResultRes interface {
	getJobExecutionResultRes()
}

type GetJobFullInfoRes interface {
	getJobFullInfoRes()
}

type GetJobResultRes interface {
	getJobResultRes()
}

type GetJobsConfigRes interface {
	getJobsConfigRes()
}

type GetJobsRes interface {
	getJobsRes()
}

type GetLobByMapRes interface {
	getLobByMapRes()
}

type GetLoginSessionRes interface {
	getLoginSessionRes()
}

type GetMapMetadataRes interface {
	getMapMetadataRes()
}

type GetMapRecordsFieldsRes interface {
	getMapRecordsFieldsRes()
}

type GetMapsRes interface {
	getMapsRes()
}

type GetPermissionRes interface {
	getPermissionRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type GetVersionRes interface {
	getVersionRes()
}

type GetVideoRes interface {
	getVideoRes()
}

type GetViewsRes interface {
	getViewsRes()
}

type InsertMapFileRecordsRes interface {
	insertMapFileRecordsRes()
}

type InsertRecordRes interface {
	insertRecordRes()
}

type ListModellingRes interface {
	listModellingRes()
}

type ListRBACResourceRes interface {
	listRBACResourceRes()
}

type ListTablesRes interface {
	listTablesRes()
}

type LoginSessionRes interface {
	loginSessionRes()
}

type LogoutSessionCompatRes interface {
	logoutSessionCompatRes()
}

type PostDatabaseRes interface {
	postDatabaseRes()
}

type PostJobReq interface {
	postJobReq()
}

type PostJobRes interface {
	postJobRes()
}

type PushLoginSessionRes interface {
	pushLoginSessionRes()
}

type PutDatabaseResourceRes interface {
	putDatabaseResourceRes()
}

type RemovePermissionRes interface {
	removePermissionRes()
}

type RemoveSessionCompatRes interface {
	removeSessionCompatRes()
}

type SearchModellingRes interface {
	searchModellingRes()
}

type SearchRecordsFieldsRes interface {
	searchRecordsFieldsRes()
}

type SearchTableRes interface {
	searchTableRes()
}

type SetConfigReq interface {
	setConfigReq()
}

type SetConfigRes interface {
	setConfigRes()
}

type SetJobsConfigRes interface {
	setJobsConfigRes()
}

type ShutdownServerRes interface {
	shutdownServerRes()
}

type StoreConfigRes interface {
	storeConfigRes()
}

type TriggerJobRes interface {
	triggerJobRes()
}

type UpdateLobByMapReq interface {
	updateLobByMapReq()
}

type UpdateLobByMapRes interface {
	updateLobByMapRes()
}

type UpdateRecordsByFieldsRes interface {
	updateRecordsByFieldsRes()
}

type UploadFileRes interface {
	uploadFileRes()
}
