# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install libpam dev
      run: |
          sudo apt-get update
          sudo apt-get install libpam0g-dev libde265-dev
          
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

#    - name: Generate
#      run: go generate .

    - name: Build
      run: make VERSION=$(grep "^VERSION" Makefile|awk '{print $3}'|sed 's/[v]//g').${{ github.ref_number }}

    - name: Test
      run: go test -v ./...

    - name: Prepare Docker
      run: make promote prepareUpload VERSION=$(grep "^VERSION" Makefile|awk '{print $3}'|sed 's/[v]//g').${{ github.ref_number }}

    - name: Build the Docker image
      run: make docker VERSION=$(grep "^VERSION" Makefile|awk '{print $3}'|sed 's/[v]//g').${{ github.ref_number }} IMAGE_NAME=thknie/cluapi:$(grep "^VERSION" Makefile|awk '{print $3}'|sed 's/[v]//g')

    - name: Login to private registry
      uses: docker/login-action@v3
      with:
#        registry: my.private.registry.com
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push the Docker image
      run: |
        docker push thknie/cluapi:$(grep ^VERSION Makefile|awk '{print $3}'|sed 's/[v]//g').${{ github.ref_number }}
  
   
