# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install libpam dev
      run: |
          sudo apt-get update
          sudo apt-get install libpam0g-dev libde265-dev
          
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

#    - name: Generate
#      run: go generate .

    - name: Build
      run: make

    - name: Test
      run: go test -v ./...

    - name: Prepare Docker
      run: make promote prepareUpload VERSION=${{ github.run_number }}

    - name: Build the Docker image
      env:
        GOOS: $(go env GOOS)
        GOARCH: $(go env GOARCH)
      run: |
        cp promote/${GOOS}_${GOARCH}/../cluapi-${GOOS}_${GOARCH}.tar.gz docker/cluapi.tar.gz;
        cd docker
        docker buildx build . 
        --file Dockerfile
        --build-arg PROJECT_VERSION="$PROJECT_VERSION"
        --tag tknie/cluapi:$(date +%s)
